mod err;
mod index;
pub mod json;
mod pokemonapi;
mod quoteapi;
mod random;
pub mod redirect;
mod sort;
mod sort_algs;
pub use err::internal_error;
pub use err::not_found;
pub use index::index as index_rs;
pub use json::example as json_example;
pub use json::ping;
pub use json::test;
pub use json::wiktrek;
pub use pokemonapi::pokemon;
pub use quoteapi::quote;
pub use random::random as random_rs;
pub use redirect::redirect as redirect_rs;
pub use sort::sort as sort_rs;
// pub use db::save;
// pub use db::delete;
